#pragma once

#define MAX_PRIORITY_LEVEL 10
#define MAX_POWER_CONSUMPTION 1000
#define MAX_LIGHTNESS 100
#define MIN_TEMPERATURE -273
#define MAX_TEMPERATURE 100
#define MAX_HUMIDITY 100
#define MAX_CO2_CONCENTRATION 1000000
#define MIN_AIR_CONDITIONING_TEMPERATURE -20
#define MAX_AIR_CONDITIONING_TEMPERATURE 40
#define MIN_AIR_CONDITIONING_SPEED 0
#define MAX_AIR_CONDITIONING_SPEED 100